; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; ~/.platformio/penv/bin/pip install intelhex
; Documentation: https://docs.platformio.org/page/projectconf.html

; Globale Defaults
[env]
framework     = arduino
monitor_speed = 115200

; ============================================
; Arduino Uno (Galaxy RVR) – Release / Debug
; ============================================

[env:uno]
platform      = atmelavr
board         = uno
upload_port   = /dev/cu.usbserial-1460
build_type    = release

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Werror=return-type
    -Wno-unused-parameter
    -Os                  ; Optimierung auf Speichergröße

lib_deps =
    bhagman/SoftPWM @ ^1.0.0
    arduino-libraries/Servo @ ^1.2.1

[env:uno-debug]
extends       = uno
platform      = atmelavr
board         = uno
framework     = arduino
build_type    = debug
upload_port   = /dev/cu.usbserial-1460
lib_deps      = ${env:uno.lib_deps}
build_flags   =
    ${env:uno.build_flags}
    -DDEBUG

; ============================================
; Seeed XIAO ESP32S3 – "Hallo Welt" & Logik Tests
; ============================================

[env:xiao_esp32s3]
platform      = espressif32
board         = seeed_xiao_esp32s3
upload_port   = /dev/cu.usbmodem14501
framework     = arduino
monitor_speed = 115200
build_type    = release

; WICHTIG: Filtert HAL heraus!
; Der ESP32 kompiliert hier nur die main.cpp.
; Er darf NICHT in src/hal schauen, da dort Uno-Code liegt.
build_src_filter =
    +<*>
    -<hal/>

build_flags =
    -std=gnu++2a
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1


lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.5

[env:xiao_esp32s3-debug]
extends       = xiao_esp32s3
platform      = espressif32
board         = seeed_xiao_esp32s3
upload_port   = /dev/cu.usbmodem14501
framework     = arduino
monitor_speed = 115200
build_type    = debug

; WICHTIG: Der Filter muss hier WIEDERHOLT werden!
; Er wird nicht automatisch geerbt.
build_src_filter =
    +<main.cpp>
    -<hal/>
    -<logic/>

lib_deps      = ${env:xiao_esp32s3.lib_deps}

build_flags   =
    -std=gnu++2a
    -DDEBUG
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
