; Globale Defaults
[env]
framework     = arduino
monitor_speed = 115200

; ============================================
; Arduino Uno (Galaxy RVR) – Release / Debug
; ============================================

; Produktion: Arduino Uno (Release)
[env:uno]
platform      = atmelavr
board         = uno
upload_port   = /dev/cu.usbserial-1460
build_type    = release

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Werror=return-type
    -Wno-unused-parameter

; Libraries: lokal fürs Projekt, nicht global installiert
lib_deps =
    bhagman/SoftPWM @ ^1.0.0
    arduino-libraries/Servo

; Debug: Arduino Uno (gleiche HW, mehr Checks/Logging)
[env:uno-debug]
extends     = uno
build_type  = debug

build_flags =
    ${env:uno.build_flags}
    -DDEBUG              ; eigenes Flag für Debug-Ausgaben


; ============================================
; Seeed XIAO ESP32S3 – Release / Debug
; ============================================

; Experimente: Seeed XIAO ESP32S3 (Release)
[env:xiao_esp32s3]
platform      = espressif32
board         = seeed_xiao_esp32s3
upload_port   = /dev/cu.usbmodem14501
framework     = arduino
monitor_speed = 115200
build_type    = release

; nur main.cpp bauen, hal/ ggf. für spätere Stufen
build_src_filter =
    +<main.cpp>
    -<hal/>

build_flags =
    -std=gnu++2a
    -DCORE_DEBUG_LEVEL=0   ; minimale Log-Ausgabe im Release

; Libraries für ESP32 hier projektspezifisch eintragen, z. B.:
; lib_deps =
;     madhephaestus/ESP32Servo@^3

extra_scripts = pre:add_python_path.py

; Debug: Seeed XIAO ESP32S3 (mehr Logging)
[env:xiao_esp32s3-debug]
extends     = xiao_esp32s3
build_type  = debug

build_flags =
    -std=gnu++2a
    -DDEBUG
    -DCORE_DEBUG_LEVEL=5   ; maximale Core-Debug-Ausgabe
